### ISSUE TITLE
Create file based change list

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1762]
We need to be able to create change list pages off of the changes we do.

Right now we have

* list of commits: https://github.com/TheSuperHackers/GeneralsGamePatch/commits/main
* list of merged pulls: https://github.com/TheSuperHackers/GeneralsGamePatch/pulls?q=is%3Apr+is%3Amerged
* handcrafted list: https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/Design/Changes/game_fixes.md

To generate properly organized change logs, we can setup json or yaml configuration for each change with some metadata, dump it into a version folder (Patch104pZH/Design/Changes/v1.0), and then implement new feature in Mod Builder that can generate change lists off of these files.

Perhaps there are python packages that already provide a framework for generating html page(s) for such use case.

Metadata can contain things like:
* title
* description
* list of things the change addresses if there is more than one
* class (tweak, balance, bugfix, etc)
* severity (minor, major, critical, blocker)
* category (art, audio, gameplay, ui, etc)
* link(s) to merged pull request
* link(s) to related issue report
* author(s)
* date

I do not think it needs to contain any media. That can remain exclusive inside pull requests and issue reports.

**Comment by xezon** [comment]
Look at existing list of labels to design metadata requirements.
https://github.com/TheSuperHackers/GeneralsGamePatch/labels

**Comment by xezon** [comment]
https://wiki.python.org/moin/StaticSiteGenerator
https://www.fullstackpython.com/static-site-generator.html

**Comment by xezon** [comment]
I think for starters we can simply generate some markdown files with changes that we can then link in the github project front page. We could have different files with different label filters and sorting orders.

For example:

all.md
art.md
audio.md
performance.md
bugfix.md
balance.md
controversial.md
usa.md
china.md
gla.md

And then simply sort the entries by date or severity or other ways.

Python should be straight forward to use to generate such markdown. We would only need to populate the data from the yaml files, and punch it with some configuration into a markdown generator.

https://github.com/Nicceboy/python-markdown-generator
https://pypi.org/project/markdownmaker/

I could need some help to create the yaml files. As of right now we will need create about 600 yaml files. That will be some monkey work for real OG monkeys.

**Comment by xezon** [comment]
This could do:

```yaml
---
# https://yaml-multiline.info/
#
# date: DD/MM/YYYY or DD-MM-YYYY
#
# labels:
# - ai
# - art
# - audio
# - blocker
# - buff
# - bug
# - china
# - controversial
# - critical
# - design
# - documentation
# - gla
# - major
# - map
# - minor
# - nerf
# - optional
# - performance
# - text
# - ui
# - usa
# - worldbuilder
#
# changes:
# - feature
# - fix
# - refactor
# - tweak

date: 09/03/2023

title: A title for this change. Optional.

brief: |-
  A brief description for this change.
  Can Take multiple lines. Optional.

changes:
  - feature: Added Overlord with 4 barrels.
  - tweak: Increased Overlord drive speed by 20%

labels:
  - buff
  - controversial
  - design
  - china

links:
  - https://github.com/TheSuperHackers/GeneralsGamePatch/issues/1754
  - https://github.com/TheSuperHackers/GeneralsGamePatch/pull/1751

authors:
  - Rich
  - Guy

```

**Comment by xezon** [comment]
On further consideration, I think title, brief and changes is too much, as it encourages writing duplicate information, when similar information is written into each of these fields just to fill them up.

I think it is better to consolidate all 3 fields into `majorchanges` list and child `minorchanges` list. This way change is concise. Author can write as many major and minor changes as he likes into file.

```yaml
---
date: 01-01-2004

majorchanges:
  - fix: avsentry model issues
    minorchanges:
      - fix: uv mapping of several meshes with house color
      - fix: uv mapping at the bottom of the vehicle
      - fix: TURRETFX01 bone position
      - fix: muzzle flash texture positions
      - fix: muzzle flash effect position
      - fix: muzzle smoke effect position
      - fix: muzzle shells effect position
      - fix: missing alpha test setting on radar dish

labels:
  - art
  - minor
  - usa

links:
  - https://github.com/TheSuperHackers/GeneralsModBuilder

authors:
  - Rich
  - Guy
```

**Comment by xezon** [comment]
I think the sublevel `minorchanges` makes this setup too complicated, also in code.

I think we can do these at the top level instead.

```yaml
majorchanges:
  - fix: avsentry model issues

minorchanges:
  - fix: uv mapping of several meshes with house color
  - fix: uv mapping at the bottom of the vehicle
  - fix: TURRETFX01 bone position
  - fix: muzzle flash texture positions
  - fix: muzzle flash effect position
  - fix: muzzle smoke effect position
  - fix: muzzle shells effect position
  - fix: missing alpha test setting on radar dish
```
